name: tilerunner
description: A random track generator built with flutter.

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: "0.12.1"
  geotools: "0.4.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/luxembourg.svg
  - assets/luxembourg.json